---
- name: Copy over Splunk installer
  copy:
    src: "files/{{ splunk_universal_forwarder_filename }}"
    dest: "/tmp/{{ splunk_universal_forwarder_filename }}"
    owner: root
    group: root
    mode: 0644

- name: Install Splunk Universal Forwarder
  apt:
    deb: "/tmp/{{ splunk_universal_forwarder_filename }}"
