---
- copy:
    src: "files/{{ splunkforwarder_filename }}"
    dest: "/tmp/{{ splunkforwarder_filename }}"
    owner: root
    group: root
    mode: 0644

- name: Install splunk universal forwarder
  apt:
    deb: "/tmp/{{ splunkforwarder_filename }}"

- template:
    src: "templates/etc/system/local/{{ item }}.conf"
    dest: "/opt/splunkforwarder/etc/system/local/{{ item }}.conf"
    owner: splunk
    group: splunk
    mode: 0644
  with_items:
    - inputs
    - outputs
  notify: Start Service | splunk
