---
- copy:
    src: "files/{{ splunkforwarder_filename }}"
    dest: "/tmp/{{ splunkforwarder_filename }}"
    owner: root
    group: root
    mode: 0644

- name: Install splunk universal forwarder
  apt:
    deb: "/tmp/{{ splunkforwarder_filename }}"

- name: Add splunk user to groups
  user:
    name: splunk
    group: splunk
    groups: adm

- name: Install custom certs
  template:
    src: "templates/etc/auth/{{ splunk_certificate_folder }}/{{ item }}.pem"
    dest: "/opt/splunkforwarder/etc/auth/{{ splunk_certificate_folder }}/{{ item }}.pem"
    owner: splunk
    group: splunk
    mode: 0644
  with_items:
    - { folder: cert, filename: ca }
    - { folder: cert, filename: fullcertificate }
  notify: Start Service | splunk
  when: splunk_use_custom_certificate

- name: copy over config
  template:
    src: "templates/etc/system/local/{{ item }}.conf"
    dest: "/opt/splunkforwarder/etc/system/local/{{ item }}.conf"
    owner: splunk
    group: splunk
    mode: 0644
  with_items:
    - inputs
    - outputs
  notify: Start Service | splunk
