---
- name: Get hostname
  command: /bin/cat /etc/hostname
  register: splunk_hostname

- name: include installer
  include: "copyinstall/{{ splunk_install_type }}.yml"

- name: Add splunk user to groups
  user:
    name: splunk
    group: splunk
    groups: adm

- name: Install custom certificates
  template:
    src: "templates/etc/auth/{{ splunk_certificate_folder }}/{{ item }}.pem"
    dest: "/opt/splunkforwarder/etc/auth/{{ splunk_certificate_folder }}/{{ item }}.pem"
    owner: splunk
    group: splunk
    mode: 0644
  with_items:
    - ca
    - fullcertificate
  notify: Start Service | splunk
  when: splunk_use_custom_certificate

- name: Copy over configuration
  template:
    src: "templates/etc/system/local/{{ item }}.conf"
    dest: "/opt/splunkforwarder/etc/system/local/{{ item }}.conf"
    owner: splunk
    group: splunk
    mode: 0644
  with_items:
    - inputs
    - outputs
  notify: Start Service | splunk
