---
- name: Get hostname | splunk
  command: /bin/cat /etc/hostname
  register: splunk_hostname

- name: include installer
  include: "copyinstall/{{ splunk_install_type }}.yml"

- name: Add splunk user to groups | splunk
  user:
    name: splunk
    group: splunk
    groups: adm

- name: Make sure certificate folder exists | splunk
  file:
    owner: splunk
    group: splunk
    path: "/opt/splunkforwarder/etc/auth/{{ splunk_certificate_folder }}"
    state: directory
    mode: 0755

- name: Install custom certificates | splunk
  template:
    src: "templates/etc/auth/{{ splunk_certificate_folder }}/{{ item }}.pem"
    dest: "/opt/splunkforwarder/etc/auth/{{ splunk_certificate_folder }}/{{ item }}.pem"
    owner: splunk
    group: splunk
    mode: 0644
  with_items:
    - ca
    - fullcertificate
  notify: Restart Service | splunk
  when: splunk_use_custom_certificate

- name: Copy over configuration | splunk
  template:
    src: "templates/etc/system/local/{{ item }}.conf"
    dest: "/opt/splunkforwarder/etc/system/local/{{ item }}.conf"
    owner: splunk
    group: splunk
    mode: 0644
  with_items:
    - inputs
    - outputs
  notify: Restart Service | splunk
